stairway_228_battery_level:
  friendly_name: 'Klimasensor gang ETG 0'
  icon_template: "mdi:battery-70"
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.stairway_228_0_229', 'battery_level') }}

living_room_234_battery_level:
  friendly_name: 'Klimasensor stue ETG 1'
  icon_template: "mdi:battery-70"
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.living_room_234_0_235', 'battery_level') }}

living_room_240_battery_level:
  friendly_name: 'Klimasensor stue ETG 2'
  icon_template: "mdi:battery-70"
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.living_room_240_0_241', 'battery_level') }}

east_252_battery_level:
  friendly_name: 'Klimasensor Ute-Øst'
  icon_template: "mdi:battery-70"
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.east_252_0_253', 'battery_level') }}

south_246_battery_level:
  friendly_name: 'Klimasensor Ute-Sør'
  icon_template: "mdi:battery-70"
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.south_246_0_247', 'battery_level') }}

north_355_battery_level:
  friendly_name: 'Klimasensor Ute-Nord'
  icon_template: "mdi:battery-70"
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.north_355_0_356', 'battery_level') }}