stairway_228_battery_level:
  friendly_name: 'Klimasensor gang ETG 0 batterinivå'
  icon_template: >-
    {% if (state_attr('binary_sensor.stairway_228_0_229', 'battery_level') > 70) %}
      mdi:battery
    {% elif (state_attr('binary_sensor.stairway_228_0_229', 'battery_level') > 50) %}
      mdi:battery-70
    {% elif (state_attr('binary_sensor.stairway_228_0_229', 'battery_level') > 20) %}
      mdi:battery-30
    {% elif (state_attr('binary_sensor.stairway_228_0_229', 'battery_level') < 20) %}
      mdi:battery-10
    {% endif %}
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.stairway_228_0_229', 'battery_level') }}

living_room_234_battery_level:
  friendly_name: 'Klimasensor stue ETG 1 batterinivå'
  icon_template: >-
    {% if (state_attr('binary_sensor.living_room_234_0_235', 'battery_level') > 70) %}
      mdi:battery
    {% elif (state_attr('binary_sensor.living_room_234_0_235', 'battery_level') > 50) %}
      mdi:battery-70
    {% elif (state_attr('binary_sensor.living_room_234_0_235', 'battery_level') > 20) %}
      mdi:battery-30
    {% elif (state_attr('binary_sensor.living_room_234_0_235', 'battery_level') < 20) %}
      mdi:battery-10
    {% endif %}
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.living_room_234_0_235', 'battery_level') }}