switch_kitchen_325_0_326_power_w:
  friendly_name: 'Oppvaskmaskin'
  icon_template: "mdi:silverware-clean"
  unit_of_measurement: "w"
  value_template: >-
    {{ state_attr("switch.kitchen_325_0_326", "current_power_w") | float }}

switch_kitchen_325_0_326_state:
  friendly_name: 'Oppvaskmaskin'
  icon_template: "mdi:silverware-clean"
  value_template: >-
    {% if (state_attr("switch.kitchen_325_0_326", "current_power_w") > 150) %}
      Oppvarming
    {% elif (state_attr("switch.kitchen_325_0_326", "current_power_w") > 3) %}
      Aktiv
    {% elif (state_attr("switch.kitchen_325_0_326", "current_power_w") > 1) %}
      På
    {% else %}
      Av
    {% endif %}