average_temperature:
  friendly_name: 'Temperatur'
  icon_template: 'mdi:thermometer'
  value_template: >-
    {{ ((
            float(states('sensor.stairway_228_0_1_230'))
          + float(states('sensor.living_room_234_0_1_236'))
          + float(states('sensor.netatmo_s71_inne_stue_temperature'))
         )  / 3) | round(1)
    }}
  unit_of_measurement: '°C'

average_humidity:
  friendly_name: 'Luftfuktighet'
  icon_template: 'mdi:water-percent'
  value_template: >-
    {{ ((
            float(states('sensor.stairway_228_0_3_232'))
          + float(states('sensor.living_room_234_0_3_238'))
          + float(states('sensor.netatmo_s71_inne_stue_humidity'))
         )  / 3) | round(0)
    }}
  unit_of_measurement: '%'