network_ping_vg:
  friendly_name: vg.no
  icon_template: mdi:pulse
  unit_of_measurement: "ms"
  value_template: >-
    {{ state_attr('binary_sensor.ping_vg', 'round_trip_time_avg') | float | round(0) }}

network_ping_google:
  friendly_name: google
  icon_template: mdi:pulse
  unit_of_measurement: "ms"
  value_template: >-
    {{ state_attr('binary_sensor.ping_google', 'round_trip_time_avg') | float | round(0) }}

network_ping_1111:
  friendly_name: 1.1.1.1
  icon_template: mdi:pulse
  unit_of_measurement: "ms"
  value_template: >-
    {{ state_attr('binary_sensor.ping_1111', 'round_trip_time_avg') | float | round(0) }}