# ETG 1
sensative_strips_guard_living_room_window_east_1:
  friendly_name: 'Vindu Øst 1'
  icon_template: >-
    {% if is_state('binary_sensor.living_room_262_0_263', 'on') %}
      mdi:window-open-variant
    {% else %}
      mdi:window-closed-variant
    {% endif %}
  value_template: >-
    {% if is_state('binary_sensor.living_room_262_0_263', 'on') %}
      Åpen
    {% else %}
      Lukket
    {% endif %}

sensative_strips_guard_living_room_window_east_1_battery_level:
  friendly_name: 'Vindussensor stue øst 1 batterinivå'
  icon_template: >-
    {% if (state_attr('binary_sensor.living_room_262_0_263', 'battery_level') > 70) %}
      mdi:battery
    {% elif (state_attr('binary_sensor.living_room_262_0_263', 'battery_level') > 50) %}
      mdi:battery-70
    {% elif (state_attr('binary_sensor.living_room_262_0_263', 'battery_level') > 20) %}
      mdi:battery-30
    {% elif (state_attr('binary_sensor.living_room_262_0_263', 'battery_level') < 20) %}
      mdi:battery-10
    {% endif %}
  unit_of_measurement: "%"
  value_template: >-
    {{ state_attr('binary_sensor.living_room_262_0_263', 'battery_level') }}