house_security:
  friendly_name: 'Alarm'
  icon_template: >-
    {% if is_state('input_boolean.house_security', 'on') %}
      mdi:shield-lock
    {% else %}
      mdi:shield-off
    {% endif %}
  value_template: "{{ is_state('input_boolean.house_security', 'on') }}"
  turn_on:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.house_security
  turn_off:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.house_security

house_secured:
  friendly_name: 'Låst'
  icon_template: >-
    {% if is_state('sensor.counter_doors_locked', '2') and is_state('sensor.counter_doors_open', '0') and is_state('sensor.counter_windows_open', '0') %}
      mdi:lock-check
    {% else %}
      mdi:lock-open
    {% endif %}
  value_template: "{{ is_state('sensor.counter_doors_locked', '2') and is_state('sensor.counter_doors_open', '0') and is_state('sensor.counter_windows_open', '0') }}"
  turn_on:
  turn_off: