house_security:
  friendly_name: 'Sikkerhet'
  icon_template: >-
    {% if is_state('input_boolean.house_security', 'on') %}
      mdi:shield-lock
    {% else %}
      mdi:shield-off
    {% endif %}
  value_template: "{{ is_state('input_boolean.house_security', 'on') }}"
  turn_on:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.house_security
  turn_off:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.house_security