# ETG 0
sensor.stairway_222_0_1_224:
  friendly_name: Temperatur

sensor.stairway_222_0_3_226:
  friendly_name: Luftfuktighet

# ETG 1
sensor.living_room_210_0_1_212:
  friendly_name: Temperatur

sensor.living_room_210_0_3_214:
  friendly_name: Luftfuktighet