# ETG 0
sensor.stairway_228_0_1_230:
  friendly_name: Temperatur

sensor.stairway_228_0_3_232:
  friendly_name: Luftfuktighet

# ETG 1
sensor.living_room_234_0_1_236:
  friendly_name: Temperatur

sensor.living_room_234_0_3_238:
  friendly_name: Luftfuktighet

# ETG 2
sensor.living_room_240_0_1_242:
  friendly_name: Temperatur

sensor.living_room_240_0_3_244:
  friendly_name: Luftfuktighet

# UTE - East
sensor.east_252_0_1_254:
  friendly_name: Temperatur

sensor.east_252_0_3_256:
  friendly_name: Luftfuktighet

sensor.east_252_0_2_255:
  friendly_name: Belysning

# UTE - South
sensor.south_246_0_1_248:
  friendly_name: Temperatur

sensor.south_246_0_3_250:
  friendly_name: Luftfuktighet

sensor.south_246_0_2_249:
  friendly_name: Belysning

# STATS
sensor.outside_min_temperature:
  friendly_name: Temperatur
  icon: mdi:thermometer

sensor.outside_avg_humidity:
  friendly_name: Luftfuktighet
  icon: mdi:water-percent

sensor.outside_avg_lux:
  friendly_name: Gjennomsnittlig belysning
  icon: mdi:weather-sunny


sensor.inside_avg_temperature:
  friendly_name: Gjennomsnittlig temperatur
  icon: mdi:thermometer

sensor.inside_avg_humidity:
  friendly_name: Gjennomsnittlig luftfuktighet
  icon: mdi:water-percent