# ETG 2
climate.living_room_135_1_1_340:
  friendly_name: 'Klima'
  icon: 'mdi:home-heart'

climate.office_nora_144_1_1_346:
  friendly_name: 'Klima'
  icon: 'mdi:home-heart'

climate.office_simen_153_1_1_343:
  friendly_name: 'Klima'
  icon: 'mdi:home-heart'