# ETG 1
switch.tv_room_181_0_182:
  icon: mdi:television
  friendly_name: TV

# ETG 2
light.living_room_177_0_178:
  icon: mdi:floor-lamp
  friendly_name: Gulvlamper

switch.bathroom_179_0_180:
  icon: mdi:power-socket-de
  friendly_name: Kontakt

switch.office_simen_173_0_174:
  icon: mdi:desktop-tower-monitor
  friendly_name: PC

switch.office_simen_175_0_176:
  icon: mdi:battery-charging-70
  friendly_name: Støvsugerlader

switch.office_nora_192_0_193:
  icon: mdi:desk
  friendly_name: Skrivebord