- platform: min_max
  name: outside_min_temperature
  type: min
  round_digits: 1
  entity_ids:
    - sensor.east_252_0_1_254
    - sensor.south_246_0_1_248
    - sensor.north_349_0_1_351

- platform: min_max
  name: outside_avg_humidity
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.east_252_0_3_256
    - sensor.south_246_0_3_250
    - sensor.north_349_0_3_353

- platform: min_max
  name: inside_avg_temperature
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.stairway_228_0_1_230
    - sensor.living_room_234_0_1_236
    - sensor.living_room_240_0_1_242

- platform: min_max
  name: outside_avg_lux
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.east_252_0_2_255
    - sensor.south_246_0_2_249
    - sensor.north_349_0_2_352

- platform: min_max
  name: inside_avg_humidity
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.stairway_228_0_3_232
    - sensor.living_room_234_0_3_238
    - sensor.living_room_240_0_3_244