# Temperature sensors
- name: vsr500_temperature_intake
  scan_interval: 30
  device_class: temperature
  slave: 1
  address: 12101
  unit_of_measurement: 째C
  count: 1
  scale: 0.1
  offset: 0
  precision: 1
  data_type: int
- name: vsr500_temperature_exhaust
  scan_interval: 30
  device_class: temperature
  slave: 1
  address: 12543
  unit_of_measurement: 째C
  count: 1
  scale: 0.1
  offset: 0
  precision: 1
  data_type: uint
- name: vsr500_temperature_return
  scan_interval: 30
  device_class: temperature
  slave: 1
  address: 12106
  unit_of_measurement: 째C
  count: 1
  scale: 0.1
  offset: 0
  precision: 1
  data_type: uint
- name: vsr500_temperature_supply_air
  scan_interval: 30
  device_class: temperature
  slave: 1
  address: 2000
  unit_of_measurement: 째C
  count: 1
  scale: 0.1
  offset: 0
  precision: 1
  data_type: uint

# Fan sensors
- name: vsr500_fan_speed_intake
  scan_interval: 30
  device_class: power_factor
  slave: 1
  address: 14000
  unit_of_measurement: '%'
  count: 1
  data_type: uint
- name: vsr500_fan_speed_exhaust
  scan_interval: 30
  device_class: power_factor
  slave: 1
  address: 14001
  unit_of_measurement: '%'
  count: 1
  data_type: uint

# Usage sensors
- name: vsr500_heat_recovery
  scan_interval: 30
  device_class: power_factor
  slave: 1
  address: 14102
  unit_of_measurement: '%'
  count: 1
  data_type: uint

# Status sensors
- name: vsr500_air_filter_countdown_s
  scan_interval: 43200
  slave: 1
  address: 7005
  unit_of_measurement: 's'
  count: 2
  data_type: uint

# Modus sensors
- name: vsr500_modus
  scan_interval: 30
  slave: 1
  address: 1160
  count: 1
  data_type: uint
- name: vsr500_modus_countdown_s
  scan_interval: 30
  slave: 1
  address: 1110
  unit_of_measurement: s
  count: 1
  data_type: uint
- name: vsr500_modus_manual_air_flow
  scan_interval: 30
  slave: 1
  address: 1130
  count: 1
  data_type: uint