homeassistant:
  # Customization file
  customize: !include_dir_merge_named customize/

http:
  use_x_forwarded_for: true
  trusted_proxies: 172.17.0.4

frontend:
  themes: !include_dir_merge_named themes/

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml

scene: !include_dir_merge_list scenes/
group: !include_dir_merge_named groups/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
counter: !include_dir_merge_named counters/
switch: !include_dir_merge_list switches/
cover: !include_dir_merge_list covers/
light: !include_dir_merge_list lights/
camera: !include_dir_merge_list cameras/

#Plugins
fibaro:
  gateways:
    - url: !secret  fibaro_url
      username: !secret fibaro_username
      password: !secret fibaro_password

netatmo:
  client_id: !secret netatmo_client_id_key
  client_secret: !secret netatmo_client_secret_key

climate:
  - platform: touchline
    host: !secret roth_touchline_ip

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

home_connect:
  client_id: !secret home_connect_client_id
  client_secret: !secret home_connect_client_secret

modbus:
  - name: VSR500
    type: tcp
    host: !secret vsr500_ip
    port: 502
    timeout: 3  #Timeout for slave response in seconds (default=3)
    delay: 3
    sensors: !include_dir_merge_list modbus/