homeassistant:
  # Customization file
  customize: !include_dir_merge_named customize/

frontend:
  themes: !include_dir_merge_named themes/

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml

scene: !include_dir_merge_list scenes/
group: !include_dir_merge_named groups/
sensor: !include_dir_merge_list sensors/
counter: !include_dir_merge_named counters/
switch: !include_dir_merge_list switches/
cover: !include_dir_merge_list covers/
light: !include_dir_merge_list lights/

#Plugins
fibaro:
  gateways:
    - url: !secret  fibaro_url
      username: !secret fibaro_username
      password: !secret fibaro_password

tibber:
  access_token: !secret tibber_token

netatmo:
  client_id: !secret netatmo_client_id_key
  client_secret: !secret netatmo_client_secret_key

speedtestdotnet: #Telenor Norge AS 12919
  scan_interval:
    minutes: 120
  monitored_conditions:
    - ping
    - download
    - upload

vacuum:
  - platform: xiaomi_miio
    host: !secret roborock_s5_ip_lingling
    token: !secret roborock_s5_token_lingling

climate:
  - platform: touchline
    host: !secret roth_touchline_ip

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret