#Ringerik-Kraft Nett:

rik_energy_transfer_cost:
  name: 'Energi overføring'
  unit_of_measurement: 'NOK/kWh'
  icon: mdi:cash-multiple
  initial: 0.2438
  min: 0
  max: 1

rik_energy_fund_cost:
  name: 'Energifond Enova'
  unit_of_measurement: 'NOK/kWh'
  icon: mdi:cash-multiple
  initial: 0.0125
  min: 0
  max: 1

rik_consumption_tax:
  name: 'Forbruksavgift'
  unit_of_measurement: 'NOK/kWh'
  icon: mdi:cash-multiple
  initial: 0.2016
  min: 0
  max: 1

rik_daily_cost:
  name: 'Fastbeløp'
  unit_of_measurement: 'NOK/dag'
  icon: mdi:cash-multiple
  initial: 6.8
  min: 0
  max: 10