blueprint:
  name: Switched on
  description: Turn on switches at given time
  domain: automation
  input:
    time_to_trigger:
      name: Time to turn on switches
      selector:
        time:
    smart_switches:
      name: Switches
      selector:
        target:
          entity:
            domain: switch

mode: single

trigger:
  - platform: time
    at: !input time_to_trigger

action:
  - service: switch.turn_on
    target: !input smart_switches